
# -*- mode: python ; coding: utf-8 -*-

import os
import sys


sqlite_binaries = []
python_dll_dir = os.path.join(sys.base_prefix, 'DLLs')
for sqlite_name in ('_sqlite3.pyd', 'sqlite3.dll'):
    sqlite_path = os.path.join(python_dll_dir, sqlite_name)
    if os.path.exists(sqlite_path):
        sqlite_binaries.append((sqlite_path, '.'))

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=sqlite_binaries,
    datas=[
        ('assets', 'assets'),
        ('qt.conf', '.'),
        ('version.txt', '.'),
        ('updater/version_manager.py', 'updater'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'PyQt6.QtCore',
        'PyQt6.QtPrintSupport',
        'PyQt6.QtSql',
        'loguru',
        'sqlite3',
        '_sqlite3',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.figure',
        'matplotlib.backends',
        'matplotlib.backends.backend_qtagg',
        'matplotlib.font_manager',
        'matplotlib.text',
        'matplotlib.colors',
        'matplotlib.lines',
        'matplotlib.patches',
        'matplotlib.axes',
        'matplotlib.axis',
        'matplotlib.ticker',
        'matplotlib.scale',
        'matplotlib.transforms',
        'matplotlib.path',
        'matplotlib.cm',
        'matplotlib.collections',
        'matplotlib.image',
        'matplotlib.legend',
        'matplotlib.gridspec',
        'matplotlib.dates',
        'matplotlib.backends.backend_agg',
        'numpy',
        'numpy._core',
        'numpy._core._multiarray_umath',
        'numpy._core.umath',
        'numpy._core.multiarray',
        'numpy._core.numeric',
        'numpy._core.fromnumeric',
        'numpy._core.shape_base',
        'numpy._core._internal',
        'numpy._core.arrayprint',
        'numpy._core.defchararray',
        'numpy._core.records',
        'numpy._core.memmap',
        'numpy._core.function_base',
        'numpy._core._dtype',
        'numpy._core._methods',
        'numpy._core._asarray',
        'numpy._core._ufunc_config',
        'numpy._core._type_aliases',
        'numpy._core._string_helpers',
        'numpy._core._exceptions',
        'numpy.version',
        'numpy._globals',
        'numpy._distributor_init',
        'numpy._typing',
        'numpy._typing._array_like',
        'numpy._typing._dtype_like',
        'numpy._typing._scalars',
        'numpy._typing._shape',
        'numpy._typing._ufunc',
        'PIL',
        'PIL.Image',
        'PIL.ImageQt',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'json',
        'hashlib',
        'subprocess',
        'threading',
        'datetime',
        'typing',
        'collections',
        'io',
        're',
        'time',
        'shutil',
        'os',
        'sys',
        'warnings',
        'traceback',
        'ctypes',
        'struct',
        'zk',
        'zk.attendance',
        'zk.base',
        'zk.const',
        'zk.exception',
        'zk.finger',
        'zk.user',
        'updater.version_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        '_tkinter',
        'tcl',
        'tk',
        'test',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
        'matplotlib.tests',
        'setuptools',
        'pkg_resources',
    ],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    name='ZAY_POS',
    debug=False,
    bootloader_ignore_signals=False,
    exclude_binaries=True,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icons/app_icon.ico' if 'assets/icons/app_icon.ico' != "NONE" else None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='ZAY_POS',
)
